### ISSUE TITLE
error module

### ISSUE THREAD

**Issue by lacalos** [mumblebaj/MMM-SweepClock#1]
Hello. I want to try your module. but there is a problem. I use page-selector and other modules .. your module despite giving it a command of where to position .. it doesn't. plus the whole figure gives me high. the circle on one side (white background circle with nothing), the hour hand in another area. so on .. can you please double check or tell me how to fix it? thank you.

**Comment by mumblebaj** [comment]
Hi. You need to show me. Please send me some screenshots. The module works great even with MMM-pages so should work fine for you as well. Please send me some screenshots and send me the config you are using for it.

**Comment by lacalos** [comment]
I can send here or only forum GitHub?

Il lun 31 gen 2022, 18:20 Bernard Mumble ***@***.***> ha
scritto:

**Comment by mumblebaj** [comment]
You can send to my email.

**Comment by lacalos** [comment]
ecco qui

Il giorno lun 31 gen 2022 alle ore 20:03 Bernard Mumble <
***@***.***> ha scritto:

**Comment by lacalos** [comment]
if you see from the config. I tell the clock to stay in a position on a
specific page .. but the module remains active from the beginning and as
you can see from the photo it is not even adjusted. all messy the image.
what can I do? thank you. yet I did exactly what it said in the readme file

Il giorno mar 1 feb 2022 alle ore 01:33 Blu Shinigami <
***@***.***> ha scritto:

**Comment by mumblebaj** [comment]
I cannot see the image nor the config. Can you try post the image here both image and config?  Also, page-selector config

**Comment by lacalos** [comment]
![2022-02-01-012406_1920x1080_scrot](https://user-images.githubusercontent.com/51279218/152707108-c663a8fb-4d4f-4be0-8191-6539495d7a3e.png)

**Comment by lacalos** [comment]
![2022-02-01-012508_1920x1080_scrot (1)](https://user-images.githubusercontent.com/51279218/152707289-4a9622b4-2fa2-44b8-9742-bbff22c88bc0.png)

**Comment by lacalos** [comment]
![2022-02-01-012406_1920x1080_scrot](https://user-images.githubusercontent.com/51279218/152707309-67bd15db-291f-4aea-ae70-d26ce313723c.png)

**Comment by lacalos** [comment]
as you can see from the config. I set that the clock module can only be seen on the sports page .. but instead it shows it everywhere and not only shows it very badly. can you help me??

**Comment by mumblebaj** [comment]
I will have a look.

Can you please provide me with the config for MMM-page-selector as well please?

**Comment by lacalos** [comment]
you see it in the picture. I take the form and tell it to stay on one page. works on everyone. I tried to put it fixed etc .. but always problems. have you tried to install it with mmm-page-selector?

**Comment by mumblebaj** [comment]
I asked for you config entry for page-selector. If you can't provide me with this config then I am unable to debug your exact config. The module work fine on it's own and with MMM-pages. MMM-pages works much in the same way as page-selector I think and yet it works fine with MMM-pages.  Please provide the config for MMM-page-selector.

**Comment by lacalos** [comment]
![2022-02-18-224109_1920x1080_scrot](https://user-images.githubusercontent.com/51279218/154767316-9d3da929-cc6e-430b-bc20-a2d18c4c7f49.png)

**Comment by mumblebaj** [comment]
I have just setup the MMM-Page-Selector module and added the config the same as yours and the clock appears fine on mine. I then created multiple pages and have it loop through the pages and the clock still appears fine. I then created multiple instances of the clock one for each page and the clock appears just fine on all pages. I unfortunately am unable to recreate the issue as you have it.

![image](https://user-images.githubusercontent.com/39963138/154794072-63639771-326f-46e3-a927-3aa36420b290.png)

**Comment by lacalos** [comment]
ok i try to delete the module and put it back from scratch. in the configuration did you put that first starts a wallpaper linked to the weather?

**Comment by mumblebaj** [comment]
No. I don't use any wallpaper. Maybe that is your problem and the issue is not with the SweepClock module.

**Comment by lacalos** [comment]
hello i tried and it doesn't work. if you have time try

**Comment by mumblebaj** [comment]
Tried what? I believe that the issue is not with the SweepClock. I cannot make changes to a module that works fine. Have you tried disabling the wallpaper and seen the clock working fine? In order to pursue this any further I need you to identify the exact module that is giving the issue or causes a conflict.

**Comment by mirrormonark** [comment]
Hello. I had the same problem. but I think I solved it... My problem is that there must be no other modules of watches otherwise it does exactly as in the photo of the other user. please can you fix it?

**Comment by mumblebaj** [comment]
That is definitely not the problem. Here I have two clock modules and the sweepclock is working just fine.

![image](https://user-images.githubusercontent.com/39963138/224503155-59f7e151-0a12-45c1-a174-5dcc023d1cdb.png)

**Comment by mirrormonark** [comment]
Yoh,goodmorning. I fixed the problem. Your module conflicts with the default clock module. If the default clock module is there, these errors result. I deleted everything and left it basic. Then I removed the default clock and put yours along with other clocks on the same page and it works fine.

**Comment by mumblebaj** [comment]
Good morning. Have you submitted a PR for this? Would be great to understand what you did to fix it. I am running a bear-bones MM install. None of the default modules on my Dev environment. If you submit a PR it would save me the time to get the environment up etc.

**Comment by mirrormonark** [comment]
Im so sorry. I expressed myself badly. I wanted to say that I found the cause of my problem. The default clock conflicts with your module clock . if I remove from my config. the module "default clock" and I put your module, everything works fine.

**Comment by mumblebaj** [comment]
No worries. I am looking at it currently. The default clock has a config for an Analog clock and the two are clashing. I am looking at fixing it. A bit of an issue as it should not be clashing as there is no cross references.  Will advise when I find a solution.

**Comment by mumblebaj** [comment]
@mirrormonark and @lacalos - Issue has been resolved. You can update the module and test alongside the default clock module.  Let me know if everything is fine now.

**Comment by mirrormonark** [comment]
sorry if I write now. I just upgraded and it works great. Thank you.

**Comment by mumblebaj** [comment]
Awesome. Thanks for the feedback.
