### ISSUE TITLE
Feature Request: Option to Disable Date Display

### ISSUE THREAD

**Issue by oanstein** [mumblebaj/MMM-SweepClock#4]
Hello

I'm using the SweepClock module and would like to request a feature: 
an option to disable the date display. This would be beneficial for users who prefer a minimalistic look with just the clock. 

Appreciate your consideration of this enhancement.

Thanks
oanstein

**Comment by mumblebaj** [comment]
Hi

I will make the update. Away on a weekend break at the moment. Will do it
when i get back.

Thank

**Comment by mumblebaj** [comment]
Hi @oanstein . I have updated module. You can now set the showDate to false to disable the date.  See README section for example config.
