### ISSUE TITLE
timezone isn't applied to analogue clock after first revolution of second hand

### ISSUE THREAD

**Issue by RaymondJSpigot** [mumblebaj/MMM-SweepClock#6]
Hi, I've updated the module to v1.1.2 with timezone support, and have specified a timezone in `config.js`. 

With the sweepclock module loaded my MagicMirror shows the expected time on the sweepclock when it is first displayed. When the second hand completes its first revolution the sweepclock hands jump to local time though.

On my test sweepclock I also have `showDate = true` with a `dateFormat: "ddd MMM D HH:mm"` and the timezone is being applied to this line correctly when the sweepclock is displayed, it's just the analogue display which jumps to the wrong time.

My `config.js` looks like

```
{
			module: "MMM-SweepClock",
			position: "bottom_bar",
			config: {
              			showDate: true,
              			dateFormat: "ddd MMM D HH:mm",
              			timezone: "Australia/Brisbane"
            		}
		},
```

e.g. with a timezone: "Australia/Brisbane" (2 hours behind New Zealand) I can see that the showDate row displays 17:05 when it's 19:05 in NZ, so that looks good.

On start-up of the MagicMirror, the analogue sweepclock shows the time in Brisbane (i.e. 5:05) but only until the second hand gets back to the 12 o'clock position.  Then the clock hands jump to show 7:06 (i.e. local time). The showDate row remains correct though.

**Comment by mumblebaj** [comment]
Good morning @RaymondJSpigot . There is one more section to update. Will update this afternoon after work. Will advise once done and pushed.

**Comment by mumblebaj** [comment]
Hi @RaymondJSpigot Should all be fixed now. Even the issue with the Date Time display has now been fixed. The time updates on that as well.

**Comment by mumblebaj** [comment]
Let me know how it goes and if all is well you can close the issue.

**Comment by RaymondJSpigot** [comment]
Hi @mumblebaj thanks very much - I've updated and tried the new clock out for a couple of days and it looks good : )  No troubles with the timezone anymore
