### ISSUE TITLE
Support for multiple instances?

### ISSUE THREAD

**Issue by RaymondJSpigot** [mumblebaj/MMM-SweepClock#7]
Now the clock can show different timezones, would it be possible to show multiple instances on a MagicMirror?  Then I could display a sweepclock next to each of several sections showing information from different countries where my family lives, e.g.

[Sweepclock] {tz = Europe/London} next to  [Weather] {location = London}

[Sweepclock {tz = Australia/Brisbane} next to [Weather] {location = Brisbane city}

[Sweepclock] {tz = New Zealand/Wellington} next to [Weather] {location = Wellington city}

sort of in a tabular layout, showing local time for each place plus the weather there.

So far I've tried adding a second MMM-SweepClock under the first one in my `config.js` - this showed 2 clocks on my mirror and the first one looks fine but the second instance does not show any clock hands.

Thanks for any assistance! regards

**Comment by mumblebaj** [comment]
Hi @RaymondJSpigot. I am currently working on another module. When I have some time I will have a look at this for you.

**Comment by mumblebaj** [comment]
@RaymondJSpigot Please send me the config you were using for the 2 instances.

Thanks

**Comment by RaymondJSpigot** [comment]
hi @mumblebaj thanks very much for taking a look : )

My test config I was trying out for 2 instances (with different timezones) looks like

```
	{
		module: "MMM-SweepClock", // clock 1, Singapore time
		position: "bottom_bar",
  		config: {
              		showDate: true, // set to true or false to show date
              		dateFormat: "dddd, LLL",
              		timezone: "Asia/Singapore"
            		}
  	},
 	{
		module: "MMM-SweepClock", // clock 2, London time
		position: "bottom_bar",
  		config: {
              		showDate: true, // set to true or false to show date
              		dateFormat: "dddd, LLL",
              		timezone: "Europe/London"
            		}
  	},
```
My `showDate` info underneath each clock is configured to include the time while I was trying it out - and looks correct for the timezone configured for each sweepclock.  
Clock hands are only displayed on sweepclock 1 though, the 2nd instance shows a clockface but no hands.  Also the clockhands shown on the first sweepclock display the time that I was expecting the 2nd instance to be showing (so in this example, clockhands on sweepclock 1 show time for timezone Europe/London)

Hope this helps : ) best regards

**Comment by mumblebaj** [comment]
@RaymondJSpigot - I have implemented multi-instance support. Have tested and it works fine.

![image](https://github.com/user-attachments/assets/15524cd7-1985-4ee8-bda6-27c3c63282fd)

Will push changes later this afternoon.

**Comment by mumblebaj** [comment]
Changes have been tested successfully and pushed. Please update to latest version 1.1.4.

**Comment by RaymondJSpigot** [comment]
Updated and tried out the latest version and it looks great : ) Thanks very much for your work on the enhancement!
